/*
 * Common defines for bare-metal [Redacted] tests.
 */

#ifndef DEFS_H
#define DEFS_H

#include <vmsa_defs.h>

T0_AS_START		= 0x00000000
T0_UART_MMIO		= 0x1c000000
T0_CODE			= 0x2e000000

T1_AS_START		= 0x80000000

// Virtual Memory layout
ZT_PAGE_VA		= 0xffffff8000000000
Z_PAGE_VA		= (ZT_PAGE_VA+TR_BLOCK_SIZE)
ZEC_PAGE_VA		= (Z_PAGE_VA+TR_BLOCK_SIZE)
ZEC_DSTPAGE_VA		= (ZEC_PAGE_VA+TR_BLOCK_SIZE)
ZEC_MAPPAGE_VA		= ZEC_DSTPAGE_VA					// 1 to 1 mapping
LOOPHOLE_CODE_SRC_VA	= (ZEC_MAPPAGE_VA+TR_BLOCK_SIZE)
LOOPHOLE_CODE_DST_VA	= (LOOPHOLE_CODE_SRC_VA+TR_BLOCK_SIZE)
LOOPHOLE_CODE_MAP_VA	= LOOPHOLE_CODE_DST_VA					// 1 to 1 mapping
PL011_UART0_VA		= (LOOPHOLE_CODE_DST_VA+TR_BLOCK_SIZE+TR_BLOCK_SIZE)

#endif	// DEFS_H
